import { MantineProvider } from "@mantine/core";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";

import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          <div
            className={"sticky top-0 backdrop-blur-md w-full z-30 mt-5 -mb-4"}
          >
            <NavBar />
          </div>
          {children}
          <div className="mt-14 w-full">
            <Footer />
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
