import { MantineProvider, createTheme, darken } from "@mantine/core";
import React from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const darkTheme = createTheme({
  primaryColor: "orange",
});

const theme = createTheme({
  shadows: {
    md: "1px 1px 3px rgba(0, 0, 0, .25)",
    xl: "5px 5px 3px rgba(0, 0, 0, .25)",
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={darkTheme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
