import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import { ColorSchemeScript } from "@mantine/core";

import { Provider } from "react-redux";
import { store, useAppSelector } from "./Redux/store";
import { ReduxProvider } from "./Redux/ReduxProvider";
import { ThemeProvider } from "./Shadcn/themeProvider";
import { MantineProvider, createTheme, darken } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const lightTheme = createTheme({
	colors: {
	},
	shadows: {
		md: "1px 1px 3px rgba(0, 0, 0, .25)",
		xl: "5px 5px 3px rgba(0, 0, 0, .25)",
	},
});

const darkTheme = createTheme({
	primaryColor: "orange",
});

const theme = createTheme({
	shadows: {
		md: "1px 1px 3px rgba(0, 0, 0, .25)",
		xl: "5px 5px 3px rgba(0, 0, 0, .25)",
	},
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	// const AppTheme = useAppSelector((state) => state.themeReducer.theme);
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript/>
			</head>
			<body className={inter.className}>
				{/* <ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				> */}
				<MantineProvider theme={darkTheme}>
					<ReduxProvider>{children}</ReduxProvider>
				</MantineProvider>
				{/* </ThemeProvider> */}
			</body>
		</html>
	);
}
