'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import { ColorSchemeScript } from "@mantine/core";

import { Provider } from "react-redux";
import { store, useAppSelector } from "./Redux/store";
import { ReduxProvider } from "./Redux/ReduxProvider";
import { ThemeProvider } from "./Shadcn/themeProvider";
import { MantineProvider, createTheme, darken } from "@mantine/core";
import Drawer from "@/components/Drawer";
import { useState } from "react";
import NavBar from "@/components/NavBar";
import AppDrawer from "@/components/Drawer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

const lightTheme = createTheme({
	colors: {
	},
	shadows: {
		md: "1px 1px 3px rgba(0, 0, 0, .25)",
		xl: "5px 5px 3px rgba(0, 0, 0, .25)",
	},
});

const darkTheme = createTheme({
	primaryColor: "orange",
});

const theme = createTheme({
	shadows: {
		md: "1px 1px 3px rgba(0, 0, 0, .25)",
		xl: "5px 5px 3px rgba(0, 0, 0, .25)",
	},
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const [showDrawer, setShowDrawer] = useState(false);
	const [stickNavBar, setStickNavBar] = useState(false);
	// const AppTheme = useAppSelector((state) => state.themeReducer.theme);
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body className={`${inter.className} no-scrollbar`}>
				<MantineProvider theme={{}}>
					<ReduxProvider>
						<AppDrawer showDrawer={showDrawer} setShowDrawer={setShowDrawer} />
						<div className={stickNavBar ? "absolute top-0 bg-red-500 " : ""}>
							<NavBar showDrawer={setShowDrawer} />
						</div>
						{children}
					</ReduxProvider>
				</MantineProvider>
			</body>
		</html>
	);
}
